name: CI Pipeline for ohip-shovel
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/ci-ohip.yml"
      - "src/**"
env:
  repo: ohip-shovel
  namespace: quicklookup
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set IMAGE_TAG as env
        run: |
          IMAGE_TAG=$(git rev-parse --short=7 ${{ github.sha }})
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: quicklookup/ohip-shovel:${{ env.IMAGE_TAG }}